version: '3.7'
services:
    workspace:
        image: 'rushlowdev/php:latest-8.1-cli'
        volumes:
            - ./:/var/htdocs
        tty: true

    php-cli:
        build:
            context: ./.docker/php-cli
        volumes:
            - ./:/var/htdocs

    php-fpm:
        image: 'rushlowdev/php:latest-8.1-fpm'
        volumes:
            - ./:/var/htdocs

    nginx:
        image: 'rushlowdev/nginx:alpine'
        volumes:
            - ./public:/var/htdocs/public
        depends_on:
            - php-fpm
        ports:
            - "80:80"
            - "443:443"

    database:
        image: 'mariadb:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306:3306'
